stages:
  - build
  - test
  - analysis
  - deploy

build:
  stage: build
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew clean classes -x test

sonarqube:
  stage: analysis
  image: core.harbor.thuni-h.com/limaofeng/gitlab-sonar-scanner
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  variables:
    GIT_DEPTH: 0
    SONAR_ANALYSIS_MODE: publish
    SONAR_BRANCH: $CI_COMMIT_REF_NAME
    SONAR_PROJECT_KEY: $CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME
  script:
    - ./gradlew clean classes -x test
    - gitlab-sonar-scanner -Dsonar.qualitygate.wait=true
  only:
    - merge_requests
    - master
  allow_failure: true

deploy:
  stage: deploy
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew artifactoryPublish
  only:
    - tags