stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle clean classes -x test
  tags:
    - shell

test:
  stage: test
  script:
    - gradle testClasses sonarqube -x test -Dsonar.host.url=http://sonar.zbsg.com.cn -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
  only:
    - tags
  tags:
    - shell

deploy:
  stage: deploy
  script:
    - gradle upload -x test
  only:
    - tags
  tags:
    - shell