stages:
  - build
  - analysis
  - deploy

variables:
  GIT_DEPTH: 0

build:
  stage: build
  image: core.harbor.thuni-h.com/library/java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew clean classes -x test
  artifacts:
    paths:
      - build
      - core/build
      - graphql/build
      - storage/build
    expire_in: 7 days
  only:
    - merge_requests
    - branches
    - tags

sonarqube:
  stage: analysis
  image: core.harbor.thuni-h.com/limaofeng/gitlab-sonar-scanner
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  script:
    - gitlab-sonar-scanner -Dsonar.qualitygate.wait=true
  only:
    - merge_requests
    - master
  allow_failure: true

deploy:
  stage: deploy
  image: core.harbor.thuni-h.com/library/java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew artifactoryPublish
  only:
    - tags