stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle clean classes -x test
  tags:
    - shell

test:
  stage: test
  script:
    - gradle sonarqube -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.scm.provider=$CI_REPOSITORY_URL -Dsonar.verbose=true
  tags:
    - shell

deploy:
  stage: deploy
  script:
    - gradle clean testClasses upload -x test
  only:
    - tags
  tags:
    - shell