stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle clean classes -x test
  tags:
    - shell

sonar:
  stage: test
  script:
    - export SONAR_OPTS="-Dsonar.gitlab.project_id=${CI_PROJECT_ID} -Dsonar.gitlab.commit_sha=${CI_BUILD_REF} -Dsonar.gitlab.ref_name=${CI_BUILD_REF_NAME} -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.verbose=true"
    - gradle sonarqube -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.scm.provider=git $SONAR_OPTS
  tags:
    - shell

deploy:
  stage: deploy
  script:
    - gradle clean testClasses upload -x test
  only:
    - tags
  tags:
    - shell