stages:
  - build
  - test
  - analysis
  - deploy

build:
  stage: build
  image: core.harbor.thuni-h.com/library/java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew clean classes -x test

sonarqube:
  stage: analysis
  image: core.harbor.thuni-h.com/library/gitlab-sonar-scanner
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew build jacocoTestReport copyDependencies
    - gitlab-sonar-scanner \
      -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*Coverage.xml' | sed 's/.*/&/' | tr '\n' ',') \
      -Dsonar.qualitygate.wait=true
  only:
    - merge_requests
    - master
  allow_failure: true

deploy:
  stage: deploy
  image: core.harbor.thuni-h.com/library/java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew publish
  only:
    - tags
