image: limaofeng/gradle-alpine

before_script:
  - echo 10.45.21.126 maven.zbsg.com.cn >> /etc/hosts

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle clean classes -x test
  tags:
    - docker

sonar:
  stage: test
  script:
    - gradle testClasses sonarqube -x test -Dsonar.host.url=http://sonar.zbsg.com.cn -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
  only:
    - tags
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - gradle upload -x test
  only:
    - tags
  tags:
    - docker