stages:
  - build
  - test
  - analysis
  - deploy

build:
  stage: build
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew clean classes -x test
  artifacts:
    paths:
      - build
      - core/build
      - graphql/build
      - storage/build
    expire_in: 7 days

sonarqube:
  stage: analysis
  dependencies:
    - build
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_ANALYSIS_MODE: publish
    SONAR_PROJECT_KEY: $CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME
  script:
    - gitlab-sonar-scanner \
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID \
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
  only:
    - master
    - develop
  allow_failure: true

deploy:
  stage: deploy
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew artifactoryPublish
  only:
    - tags