stages:
  - build
  - test
  - analysis
  - deploy

variables:
  GIT_DEPTH: 0

build:
  stage: build
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew clean classes -x test
  artifacts:
    paths:
      - build
      - core/build
      - graphql/build
      - storage/build
    expire_in: 7 days

sonarqube:
  stage: analysis
  dependencies:
    - build
  image: core.harbor.thuni-h.com/limaofeng/gitlab-sonar-scanner
  variables:
    SONAR_ANALYSIS_MODE: publish
    SONAR_BRANCH: $CI_COMMIT_REF_NAME
    SONAR_PROJECT_KEY: $CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME
  script:
    - gitlab-sonar-scanner -X
  only:
    - merge_requests
    - master
  allow_failure: true

deploy:
  stage: deploy
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew artifactoryPublish
  only:
    - tags