stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle clean classes -x test
  tags:
    - shell

test:
  stage: test
  script:
    - gradle sonarqube -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.scm.provider=git -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.verbose=true
  tags:
    - shell

deploy:
  stage: deploy
  script:
    - gradle clean testClasses upload -x test
  only:
    - tags
  tags:
    - shell