stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew clean classes -x test

sonarqube:
  stage: test
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_ANALYSIS_MODE: publish
    SONAR_PROJECT_KEY: $CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME
  script:
    - gitlab-sonar-scanner
  only:
    - master
    - develop
  allow_failure: true

deploy:
  stage: deploy
  image: java:8
  cache:
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  before_script:
    - export GRADLE_USER_HOME=$PWD/.gradle
  script:
    - ./gradlew artifactoryPublish
  only:
    - tags