spring:
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://dev.local:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: yV2jJxvNs8BD
    druid:
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      minIdle: 1
  redis:
    host: dev.local
    port: 6379
    password: sOmE_sEcUrE_pAsS

graphql:
  servlet:
    mapping: /graphql
    enabled: true