server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      connection-timeout: 30000
      minimum-idle: 50
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4
  data:
    redis:
      jedis:
        pool:
          max-active: 8
          max-wait: 300
          max-idle: 100
          min-idle: 100
      connect-timeout: 1000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
        jdbc:
          time_zone: GMT+8
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        cache:
          use_query_cache: false
          use_second_level_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    open-in-view: false
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

management:
  health:
    elasticsearch:
      enabled: false

graphql:
  servlet:
    exception-handlers-enabled: true
    cors-enabled: true
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: GET, HEAD, POST
      allowed-headers: Accept, Origin, Authorization, Content-Type, Last-Modified, X-API-KEY
      allow-credentials: true
      max-age: 3600
  tools:
    introspection-enabled: true
  graphiql:
    subscriptions:
      reconnect: true
      timeout: 30
    endpoint:
      subscriptions: /subscriptions

logging:
  config: classpath:logback.xml


