spring:
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://dev.local:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: yV2jJxvNs8BD
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  redis:
    host: dev.local
    port: 6379
    password: sOmE_sEcUrE_pAsS
  cuckoo:
    elasticsearch:
      client:
        url: https://es.thuni-h.com:9200
        api-key: RWpsR3dvQUJINEtJY2FvWGJGMXg6QkNXZzJ0X01UY2VocFNBQUVXNGExQQ==
        ssl:
          certificate-path: /Users/limaofeng/Downloads/ca/ca.crt
    enable: false

graphql:
  servlet:
    mapping: /graphql
    enabled: true