spring:
  tomcat:
    disableSession: false
  config:
    import: optional:file:.env[.properties]
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_INSTANCE_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
    #    proxy: true
    sharding: true
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
      database: 0
  quartz:
    jdbc:
      initialize-schema: always
#  shardingsphere:
#    datasource:
#      names: dynamicDataSource
#    sharding:
#      tables:
#        sys_user:
#          database-strategy:
#            inline:
#              sharding-column: tenant_id
#              algorithmExpression: myDatabaseShardingAlgorithms
  security:
    access-token:
      refresh: false


cuckoo:
  elasticsearch:
    client:
      url: https://es.thuni-h.com:9200
      api-key: RWpsR3dvQUJINEtJY2FvWGJGMXg6QkNXZzJ0X01UY2VocFNBQUVXNGExQQ==
      ssl:
        certificate-path: /Users/limaofeng/Downloads/ca/ca.crt
  enable: false