server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connection-init-sqls:
        - set names utf8mb4
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: 300
        max-idle: 100
        min-idle: 100
      timeout: 1000
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        open-in-view: true
        jdbc:
          time_zone: GMT+8
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        cache:
          use_query_cache: false
          use_second_level_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        dialect: org.hibernate.dialect.MySQL55Dialect
        show_sql: true
    generate-ddl: false
    open-in-view: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

graphql:
  servlet:
    websocket:
      enabled: false
    exception-handlers-enabled: true
    cors-enabled: true
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: GET, HEAD, POST
      allowed-headers: Accept, Origin, Authorization, Content-Type, Last-Modified
      allow-credentials: true
      max-age: 3600
  tools:
    introspection-enabled: true

logging:
  config: classpath:logback.xml
  file:
    path: ./log


