spring:
  tomcat:
    disableSession: false
  config:
    import: optional:file:.env[.properties]
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_INSTANCE_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
    #    proxy: true
    sharding: true
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
      database: 0
  quartz:
    jdbc:
      initialize-schema: always
#  shardingsphere:
#    datasource:
#      names: dynamicDataSource
#    sharding:
#      tables:
#        sys_user:
#          database-strategy:
#            inline:
#              sharding-column: tenant_id
#              algorithmExpression: myDatabaseShardingAlgorithms
  security:
    access-token:
      refresh: false


cuckoo:
  elasticsearch:
    client:
      url: https://es.thuni-h.com:9200
      api-key: RWpsR3dvQUJINEtJY2FvWGJGMXg6QkNXZzJ0X01UY2VocFNBQUVXNGExQQ==
      ssl:
        certificate-path: /Users/limaofeng/Downloads/ca/ca.crt
  enable: false

graphql:
  gateway:
    config-location: classpath:graphql-gateway.yaml
    security:
      authentication:
        enabled: false
        providers:
          - name: "api-key"
            type: "api-key"
            header: "X-API-KEY"
          - name: "oidc"
            type: "oidc"
            issuer-uri: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_1a2b3c4d5e6f7g8h"
            client-id: "client-id"
            client-secret: "client-secret"
          - name: "user-pools"
            type: "user-pools"
            user-pool-id: "ap-northeast-1_1a2b3c4d5e6f7g8h"
            app-client-id: "client-id"
            app-client-secret: "client-secret"
      authorization:
        enabled: false
        default-policy-effect: "deny"
        public-paths:
          - "/public/**"
          - "/home"
          - "/about-us"
        policies-location: classpath:auth-policy.yaml
        roles:
          - id: "admin"
            description: "Admin role"
            permissions:
              - "policy-1"
              - "policy-2"
              - "policy-3"
          - id: "user"
            description: "User role"
            permissions:
              - "policy-2"
          - id: "product-manager"
            description: "Product manager role"
            permissions:
              - "policy-3"