spring:
  tomcat:
    disableSession: false
  config:
    import: optional:file:.env[.properties]
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_INSTANCE_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
#    proxy: true
    sharding: true
  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
    database: 0
#  shardingsphere:
#    datasource:
#      names: dynamicDataSource
#    sharding:
#      tables:
#        sys_user:
#          database-strategy:
#            inline:
#              sharding-column: tenant_id
#              algorithmExpression: myDatabaseShardingAlgorithm


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    cors-enabled: true
    cors:
      allowed-origins:
        - "*"
      allowed-methods: GET, HEAD, POST
      allow-credentials: false
    exception-handlers-enabled: true

cuckoo:
  elasticsearch:
    client:
      url: https://192.168.5.7:9200
      api-key: eGhzZjFZMEJFWW50eEFqVkRzb0E6R1o5SmppWklUb216Z3dCWHZJVVpvZw==
      ssl:
        certificate-path: /Users/limaofeng/Downloads/ca/ca.crt
  enable: true